# Generated by Django 6.0.2 on 2026-04-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_timesheetactivity_compoffrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='leave_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
