# Generated by Django 6.0.2 on 2026-04-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancerecord_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetactivity',
            name='sub_activity',
            field=models.TextField(blank=True, default=''),
        ),
    ]
