# Generated by Django 6.0.2 on 2026-04-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_timesheetactivity_sub_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='ts_check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='ts_check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
