# Generated by Django 6.0.2 on 2026-04-20 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancerecord_ts_check_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_check_in', models.DateTimeField(blank=True, null=True)),
                ('ts_check_out', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_derived', to='attendance.attendancerecord')),
            ],
        ),
    ]
